# Compose的版本
version: "3"

# 定义服务
services:
  mysql:
    container_name: oriental_wealth_mysql
    image: mysql:8.0.32
    # 环境变量
    env_file: .env
    volumes:
      - /home/zingfront/zhangjian/mysql_config/conf.d:/etc/mysql/conf.d
      - /home/zingfront/zhangjian/mysql_data:/var/lib/mysql
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口，格式:`宿主机:容器`
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "oriental_wealth_mysql"]
      interval: 1s
      timeout: 3s
      retries: 30
  spider:
    container_name: oriental_wealth
    # Dockerfile 的目录，用于构建镜像
    build: .
    environment:
      - SCRAPY_PROJECT=default
    volumes:
      - /home/zingfront/zhangjian/oriental_logs:/home/code/oriental_wealth/logs
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      .spider_env
